// <auto-generated />
namespace PrivateLessonsEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StudentsCreatedDateaddToDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentsCreatedDateaddToDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201706262011294_Students-CreatedDate(addToDB)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
